### ISSUE TITLE
Minor CU change tracking

### ISSUE THREAD

**Issue by raghup17** [raghup17/plasticine#4]
Plasticine:
- [x] Parameterize input data buses. Same parameter should govern number of scratchpads too.
- [x] Parameterize memory generation.
- [x] Decouple input data buses from scratchpads with a crossbar.
- [ ] Forward empty stage's reg values to rwStages+1
- [ ] Connect counter max and stride values from the first lane's empty stage registers.
- [x] Drive dataOut from r1 of the last stage.
- [ ] Add ability to turn off lane, stage, register
- [x] Remove 'wStages' parameter

PISA:
- [ ]  Standardize register naming convention across stages - pipeline regs come first
- [ ] Support x == don't care everywhere
- [ ] Add accumInit support to initialize accumulator

**Comment by blackwings-01** [comment]
In case you don't remember (which I didn't until I looked at generated pisa), tokenOutLUTs are 2 to 1 LUTs rather than numCtr to 1 LUTs because it always only depends on less than equals to two signals

**Comment by raghup17** [comment]
Yup, that's the way it is in the architecture and the block diagram now.
The input is parsed as the config for a 2-input LUT.
